// FOR YTS SERVER
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIE = 'GET_MOVIE';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
// FOR EXPRESS SERVER
export const GET_DOWNLOADING_MOVIES = 'GET_DOWNLOADING_MOVIES';
export const GET_DOWNLOAD_QUEUE_MOVIES = 'GET_DOWNLOAD_QUEUE_MOVIES';
export const POST_MOVIE = 'POST_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const DELETE_DOWNLOADING_MOVIE = "DELETE_DOWNLOADING_MOVIE";
